DROP TABLE IF EXISTS users_in_car1 CASCADE;
DROP TABLE IF EXISTS cars1 CASCADE;
DROP TABLE IF EXISTS PS1 CASCADE;


CREATE TABLE users_in_car1 (
  id  SERIAL PRIMARY KEY ,
  firstname VARCHAR NOT NULL,
  lastname  VARCHAR NOT NULL
);
CREATE TABLE cars1 (
  id  SERIAL PRIMARY KEY ,
  userid INTEGER NOT NULL,
  model  VARCHAR,
  colour VARCHAR,
  FOREIGN KEY (userid) REFERENCES users_in_car1 (id) ON DELETE CASCADE

);

CREATE TABLE PS1 (
  id SERIAL PRIMARY KEY ,
  carid  INTEGER NOT NULL,
  price  INTEGER,
  time1  TIMESTAMP,
  time2  TIMESTAMP,
  FOREIGN KEY (carid) REFERENCES cars1(id) ON DELETE CASCADE

)